# Generated by Django 4.2.30 on 2026-04-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Сумма скидки', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
