# Generated by Django 4.2.10 on 2026-04-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('ONE SIZE', 'ONE SIZE')], max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
